<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function mfasiri_preprocess_page_title(&$variables)
{
    $routeObject = Drupal::routeMatch()->getRouteObject();
    $view_id = $routeObject->getDefault('view_id');
    $display_id = $routeObject->getDefault('display_id');
    if ($view_id == 'ibiganiro' and $display_id == 'page_duhugurane') {
        $variables['topics_page'] = true;
    }
}
